#!/bin/bash

# Script:                       Ops 301 Ops Chall 02
# Author:                       Courtney Johnson    
# Date of latest revision:      04/25/2022
# Purpose:                      Prompts user for input directory path

# How to view file permissions

ls -al

# Add file name if you want to filter the view

ls -al testfile.txt

# How to set file permissions to a single file

chmod 777 testfile.txt

# How to set file permissions on this directory and all its contents

chmod -R 755 ./

#Prints to the screen the directory contents and the new permissions settings of everything in the directory.
printf 
